### ISSUE TITLE
关于 Shadowsocks 服务端的问题

### ISSUE THREAD

**Issue by Pastechn** [ColetteContreras/ssp#1]
之前一直用的 Poseidon V2ray 服务端手动配置的 Shadowsocks ，但是只能单用户。于是换用了 SSP 服务端，多用户连接表现正常。使用 OpenWRT 上的 SSRP+ 连接，并开启 Socks5 服务端，可正常浏览网页，且 Telegram 工作正常。但是使用 XShell 连接 Socks5 时无法正常工作，出现下列提示：
```
Connection closing...Socket close
```
以为是客户端的问题，于是换用 v2rayN 进行连接，开启本地 Socks5 代理，提示：
```
failed to read IV > EOF
```
换用原本的 Poseidon 单端口单用户方案后，所有连接均表现正常。

**Comment by ColetteContreras** [comment]
> 但是使用 XShell 连接 Socks5 时无法正常工作

这个没用过，可以使用 curl 测试一下 socks5 的代理，看有没有问题。

```
curl --proxy socks5h://localhost:1080 https://ifconfig.co/json
```
